### ISSUE TITLE
agregar un movimiento con causa transferencia tira un stacktrace

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#292]
NoMethodError in Movimientos#new Showing /home/fauno/Proyectos/lainventoria/cp/app/views/movimientos/_transferencia.html.erb where line #8 raised: undefined method `last' for nil:NilClass Rails.root: /home/fauno/Proyectos/lainventoria/cp Application Trace app/models/caja.rb:69:in`banco_tipo_numero' app/views/movimientos/_transferencia.html.erb:8:in `block in _app_views_movimientos__transferencia_html_erb__909620952__627174888' app/views/movimientos/_transferencia.html.erb:3:in`_app_views_movimientos__transferencia_html_erb__909620952__627174888' app/controllers/movimientos_controller.rb:10:in `block (2 levels) in new' app/controllers/movimientos_controller.rb:8:in`new' Framework Trace vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:761:in `value_for_collection' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:397:in`block in options_from_collection_for_select' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/relation/delegation.rb:46:in `map' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/relation/delegation.rb:46:in`map' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:396:in `options_from_collection_for_select' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/tags/collection_select.rb:21:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:204:in `collection_select' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:791:in`collection_select' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `block in capture' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:200:in`with_output_buffer' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `capture' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_helper.rb:699:in`fields_for' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/template.rb:145:in `block in render' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:161:in`instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/template.rb:339:in `instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/template.rb:143:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/partial_renderer.rb:279:in`block in render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`block in instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/partial_renderer.rb:278:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/renderer.rb:47:in `render_partial' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/renderer.rb:21:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/rendering.rb:99:in `_render_template' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/streaming.rb:217:in`_render_template' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/rendering.rb:82:in `render_to_body' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rendering.rb:32:in`render_to_body' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/renderers.rb:32:in `render_to_body' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/rendering.rb:25:in`render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rendering.rb:16:in `render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:41:in`block (2 levels) in render' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms' /usr/lib/ruby/2.0.0/benchmark.rb:296:in`realtime' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:41:in`block in render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:40:in `render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/mime_responds.rb:258:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/mime_responds.rb:258:in `respond_to' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/implicit_render.rb:4:in`send_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/base.rb:189:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rendering.rb:10:in`process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:113:in`call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:113:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:86:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:86:in`run_callbacks' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rescue.rb:29:in`process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`block in instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`instrument' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/params_wrapper.rb:250:in`process_action' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/base.rb:136:in`process' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/rendering.rb:30:in `process' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal.rb:196:in`dispatch' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal.rb:232:in`block in action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in`dispatch' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:50:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/journey/router.rb:71:in`block in call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in `each' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:678:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/etag.rb:23:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/conditionalget.rb:25:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/head.rb:11:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/flash.rb:254:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context' vendor/ruby/2.0.0rack (1.5.2) lib/rack/session/abstract/id.rb:220:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/cookies.rb:560:in `call' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/query_cache.rb:36:in`call' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/migration.rb:380:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:82:in`run_callbacks' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/reloader.rb:73:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/remote_ip.rb:76:in `call' vendor/ruby/2.0.0better_errors (1.1.0) lib/better_errors/middleware.rb:58:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call' vendor/ruby/2.0.0railties (4.1.4) lib/rails/rack/logger.rb:38:in `call_app' vendor/ruby/2.0.0railties (4.1.4) lib/rails/rack/logger.rb:20:in`block in call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `block in tagged' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/tagged_logging.rb:26:in`tagged' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `tagged' vendor/ruby/2.0.0railties (4.1.4) lib/rails/rack/logger.rb:20:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/request_id.rb:21:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/methodoverride.rb:21:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/runtime.rb:17:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/lock.rb:17:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/static.rb:64:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/sendfile.rb:112:in `call' vendor/ruby/2.0.0railties (4.1.4) lib/rails/engine.rb:514:in`call' vendor/ruby/2.0.0railties (4.1.4) lib/rails/application.rb:144:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/lock.rb:17:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/content_length.rb:14:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/handler/webrick.rb:60:in`service' /usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service' /usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in`run' /usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread' Full Trace app/models/caja.rb:69:in`banco_tipo_numero' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:761:in `value_for_collection' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:397:in`block in options_from_collection_for_select' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/relation/delegation.rb:46:in `map' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/relation/delegation.rb:46:in`map' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:396:in `options_from_collection_for_select' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/tags/collection_select.rb:21:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:204:in `collection_select' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_options_helper.rb:791:in`collection_select' app/views/movimientos/_transferencia.html.erb:8:in `block in _app_views_movimientos__transferencia_html_erb__909620952__627174888' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in`block in capture' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in`capture' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/helpers/form_helper.rb:699:in `fields_for' app/views/movimientos/_transferencia.html.erb:3:in`_app_views_movimientos__transferencia_html_erb__909620952__627174888' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/template.rb:145:in `block in render' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:161:in`instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/template.rb:339:in `instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/template.rb:143:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/partial_renderer.rb:279:in`block in render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`block in instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/partial_renderer.rb:278:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/renderer.rb:47:in `render_partial' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/renderer/renderer.rb:21:in`render' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/rendering.rb:99:in `_render_template' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/streaming.rb:217:in`_render_template' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/rendering.rb:82:in `render_to_body' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rendering.rb:32:in`render_to_body' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/renderers.rb:32:in `render_to_body' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/rendering.rb:25:in`render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rendering.rb:16:in `render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:41:in`block (2 levels) in render' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms' /usr/lib/ruby/2.0.0/benchmark.rb:296:in`realtime' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:41:in`block in render' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:40:in `render' app/controllers/movimientos_controller.rb:10:in`block (2 levels) in new' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/mime_responds.rb:258:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/mime_responds.rb:258:in`respond_to' app/controllers/movimientos_controller.rb:8:in `new' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/implicit_render.rb:4:in`send_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/base.rb:189:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rendering.rb:10:in`process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:113:in`call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:113:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:229:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:166:in`block in halting' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:86:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:86:in`run_callbacks' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rescue.rb:29:in`process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`block in instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/notifications.rb:159:in`instrument' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/params_wrapper.rb:250:in`process_action' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action' vendor/ruby/2.0.0actionpack (4.1.4) lib/abstract_controller/base.rb:136:in`process' vendor/ruby/2.0.0actionview (4.1.4) lib/action_view/rendering.rb:30:in `process' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal.rb:196:in`dispatch' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_controller/metal.rb:232:in`block in action' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in`dispatch' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:50:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/journey/router.rb:71:in`block in call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in `each' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:678:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/etag.rb:23:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/conditionalget.rb:25:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/head.rb:11:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/flash.rb:254:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context' vendor/ruby/2.0.0rack (1.5.2) lib/rack/session/abstract/id.rb:220:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/cookies.rb:560:in `call' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/query_cache.rb:36:in`call' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call' vendor/ruby/2.0.0activerecord (4.1.4) lib/active_record/migration.rb:380:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/callbacks.rb:82:in`run_callbacks' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/reloader.rb:73:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/remote_ip.rb:76:in `call' vendor/ruby/2.0.0better_errors (1.1.0) lib/better_errors/middleware.rb:58:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call' vendor/ruby/2.0.0railties (4.1.4) lib/rails/rack/logger.rb:38:in `call_app' vendor/ruby/2.0.0railties (4.1.4) lib/rails/rack/logger.rb:20:in`block in call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `block in tagged' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/tagged_logging.rb:26:in`tagged' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `tagged' vendor/ruby/2.0.0railties (4.1.4) lib/rails/rack/logger.rb:20:in`call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/request_id.rb:21:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/methodoverride.rb:21:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/runtime.rb:17:in `call' vendor/ruby/2.0.0activesupport (4.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/lock.rb:17:in `call' vendor/ruby/2.0.0actionpack (4.1.4) lib/action_dispatch/middleware/static.rb:64:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/sendfile.rb:112:in `call' vendor/ruby/2.0.0railties (4.1.4) lib/rails/engine.rb:514:in`call' vendor/ruby/2.0.0railties (4.1.4) lib/rails/application.rb:144:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/lock.rb:17:in`call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/content_length.rb:14:in `call' vendor/ruby/2.0.0rack (1.5.2) lib/rack/handler/webrick.rb:60:in`service' /usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service' /usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in`run' /usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread' Request parameters {"causa_tipo"=>"transferencia", "factura_id"=>"2"}

**Comment by fauno** [comment]
esto lo hice desde develop
